ros_docker_images/templates/docker_images/create_gzserverX_image.Dockerfile.em
ros_docker_images/templates/docker_images/create_gzserver_image.Dockerfile.em
ros_docker_images/templates/docker_images/create_ros2_image.Dockerfile.em

Use ubuntu-stable from packages.osrfoundation.org

---

ros_docker_images/templates/docker_images/create_ros_core_image.Dockerfile.em
ros_docker_images/templates/docker_images/create_ros_image.Dockerfile.em

ros images will be able to share additional layers (about 90MB)
Pending on https://github.com/osrf/docker_images/pull/31

Moving ros distro EVN to preserve more cache and adding arg for MAINTAINER  

---

docker_templates/argparse.py
docker_templates/create.py
docker_templates/templates/docker_library/ros.em

See https://github.com/osrf/docker_images/pull/66

Adding files for ros multi-arch manifest generation

---

docker_templates/templates/docker_images/create_ros2_image.Dockerfile.em
docker_templates/templates/docker_images/ros1_bridge_entrypoint.sh

Relates to https://github.com/osrf/docker_images/pull/77

Adding source for ros1 to ros2_bridge entry point.

---

docker_templates/create.py
docker_templates/folders.py
docker_templates/library.py
docker_templates/templates/docker_images/create_ros2_image.Dockerfile.em
docker_templates/templates/docker_images/ros1_bridge_entrypoint.sh
docker_templates/templates/docker_library/gazebo.em
docker_templates/templates/docker_library/ros.em
docker_templates/templates/docker_library/ros2.em

to share more common functions

Refactoring Library scripts

---

README.md
setup.py

fixup for README and setup.py

---

docker_templates/templates/docker_images/create_gzweb_image.Dockerfile.em

Related: https://github.com/osrf/docker_images/issues/97#issuecomment-341215696

Updating gzweb launch command

---

docker_templates/folders.py
docker_templates/library.py
docker_templates/templates/docker_library/gazebo.em
docker_templates/templates/docker_library/ros.em
docker_templates/templates/docker_library/ros2.em

Needed to be able to run `create_dockerfolders.py` once e.g. https://github.com/osrf/docker_images/pull/109 is merged

support empty tag_names dict from manifest

---

docker_templates/templates/docker_images/create_ros2_image.Dockerfile.em

fixing missing default command for bridge image

Ros2 entrypoint cleaning

---

docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em

Context https://github.com/ros2/rosdistro/issues/492

Reintegrate with ros/rosdistro repo

---

docker_templates/templates/docker_images_ros2/source/create_ros_image.Dockerfile.em
docker_templates/templates/snippet/vcs_import.Dockerfile.em

Relates to https://github.com/osrf/docker_images/pull/242

Set ROS_DISTRO env from config

---

docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em

The evaluation of the dependencies depends not only on `ROS_DISTRO` but also other env variables like `ROS_PYTHON_VERSION` (e.g. https://github.com/osrf/osrf_pycommon/blob/f037f185a7134b113682328ed3b9885eb02eb334/package.xml#L14), so it is preferred to have the setup files sourced before calling `rosdep install`.
Generated dockerfiles available at https://github.com/osrf/docker_images/pull/255
@ruffsl this is also going back to custom rosdep install commands instead of using the template

source ros-workspace before calling rosdep

---

docker_templates/templates/docker_images_ros2/source/create_ros_image.Dockerfile.em

Based on discussion from https://github.com/osrf/docker_images/pull/255

set ROS_VERSION and ROS_PYTHON_VERSION

---

docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em

needed for the nightly image to build, see https://github.com/osrf/docker_images/pull/261

use ros2-testing apt repo for nightly image

---

docker_templates/templates/snippet/vcs_import.Dockerfile.em

Generated dockerfiles from this change available at https://github.com/osrf/docker_images/pull/271

update default ros2.repos URL

---

docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em

More details at https://github.com/osrf/docker_images/pull/307

[nightly] use custom rosdistro_index_url

---

docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
docker_templates/templates/snippet/install_ros_bootstrap_tools.Dockerfile.em

Context: https://github.com/osrf/docker_images/issues/313
Related: https://github.com/osrf/docker_images/pull/315

Add and setup colcon mixin and metadata in templates

---

docker_templates/eol_distro.py

Last crystal sync happened https://discourse.ros.org/t/new-packages-and-patch-release-for-ros-2-crystal-clemmys/11927

add crystal to eol distro list

---

docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em

Template change enabling https://github.com/osrf/docker_images/pull/349

Remove ros workspace

---

docker_templates/templates/docker_images_ros2/ros1_bridge/create_ros_ros1_bridge_image.Dockerfile.em

add ability to install non-ROS downstream packages in ros1-bridge image

---

docker_templates/templates/docker_images/create_drcsim_image.Dockerfile.em
docker_templates/templates/docker_images/create_gzclient_image.Dockerfile.em
docker_templates/templates/docker_images/create_gzserverX_image.Dockerfile.em
docker_templates/templates/docker_images/create_gzserver_image.Dockerfile.em
docker_templates/templates/docker_images/create_gzweb_image.Dockerfile.em
docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
docker_templates/templates/snippet/install_upstream_package_list.Dockerfile.em
docker_templates/templates/snippet/label_and_install_package_list.Dockerfile.em

See https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md#rules
Related: https://github.com/docker-library/official-images/pull/8786#issuecomment-700238992

Use reverse dns label

---

docker_templates/templates/snippet/label_and_install_package_list.Dockerfile.em

Comment out labels

---

docker_templates/templates/docker_images_ros2/testing/create_ros_image.Dockerfile.em
docker_templates/templates/docker_images_ros2/testing/ros_entrypoint.sh
docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em

Needed for https://github.com/osrf/docker_images/pull/542

Allow using testing APT repo and provide template for testing image

---

docker_templates/templates/docker_images/create_ros_image.Dockerfile.em
docker_templates/templates/snippet/install_ros_bootstrap_tools.Dockerfile.em

add hack to install python3 packages on ROS Noetic

---

docker_templates/templates/docker_images/ros_entrypoint.sh
docker_templates/templates/docker_images_ros2/devel/ros_entrypoint.sh
docker_templates/templates/docker_images_ros2/nightly/ros_entrypoint.sh
docker_templates/templates/docker_images_ros2/ros1_bridge/ros_entrypoint.sh
docker_templates/templates/docker_images_ros2/ros_entrypoint.sh
docker_templates/templates/docker_images_ros2/testing/ros_entrypoint.sh

Related to https://github.com/osrf/docker_images/issues/626

add -- to fix positional argument forwarding

---

docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
docker_templates/templates/snippet/setup_ros_sync_date.Dockerfile.em

Parser ros/rosdistro tags to extract the latest sync date for a given distro and injects it in the dockerfile by setting the environment varialbe ROS_SYNC_DATE

Add logic to add ROSDISTRO_PKGS_SYNC_DATE to ros_core images
