osrf/docker_templates

- ros_docker_images/templates/docker_images/create_ros2_image.Dockerfile.em
The xenial docker image is very minimal, and doesn't ship with lsb_release.
This is needed for https://github.com/osrf/docker_images/pull/37
> Updating the ROS2 image to work with alpha7

- ros_docker_images/templates/docker_images/create_drcsim_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzclient_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzserverX_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzserver_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzweb_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros2_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros_core_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros_image.Dockerfile.em
Reverts osrf/docker_templates#9
This is not really necessary since the base Docker images already clean up the APT cache after fetching the packages.
> Revert "Removed deb packages from the APT cache"

- ros_docker_images/templates/docker_images/create_base_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzserverX_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros2_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros_core_image.Dockerfile.em
ubuntu doesn't ship `locales` in its image anymore. We need to install it ourselves otherwise the docker images cannot be built. (see https://github.com/ros-infrastructure/ros_buildfarm/pull/415)
> install locales before calling locale-gen

- ros_docker_images/templates/docker_images/create_base_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzserverX_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros_core_image.Dockerfile.em
Looks like ubuntu ships with C.UTF-8, is it pertinent that our official images include en_US.UTF-8?
https://botbot.me/freenode/docker-library/2017-05-23/?msg=86040387&page=1
The whole stack of dockerfiles for lunar builds fine with this template, but this may be more of a runtime requirement. Any real reason that necessitates en_US.UTF-8 ? I thought this just needed to be set to something that supports unicode. 
https://community.hpe.com/t5/General/Difference-between-C-utf8-and-en-us-utf8-points/td-p/4418194
> Install locales round2

- ros_docker_images/templates/docker_images/create_gzserver_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzweb_image.Dockerfile.em
Having the template look into the etc files for distro version info instead of the lsb-release command.
https://www.freedesktop.org/software/systemd/man/os-release.html
However ubuntu 14.04 doesn't have all the modern verabels set, thus the need for sourcing both /etc/lsb-release and /etc/os-release.
> Removing lsb-release package requirement

- ros_docker_images/templates/docker_images/create_drcsim_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzclient_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzserverX_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzserver_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzweb_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros2_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros_core_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros_image.Dockerfile.em
To enable auto Dockerfile diff checking for things like version bumps
having changed the template primitive accordingly https://github.com/ruffsl/ros_buildfarm/commit/e850eba6b88e54a9b60e2063031b31da9a69ab92
> Omitting timestamp

- ros_docker_images/templates/docker_images/create_drcsim_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzserverX_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_gzserver_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros2_image.Dockerfile.em
- ros_docker_images/templates/docker_images/create_ros_core_image.Dockerfile.em
to better support building dockerfiles behind firewalls.
Also leaving no old examples behind to avoid others from copying old style from templates
See https://github.com/osrf/docker_images/pull/62 for context
> Updating keyserver URL to p80 pool

- docker_templates/templates/docker_images/create_ros_eol_image.Dockerfile.em
old ubuntu images seem to still have locale-gen still pre-installed.
> Reverting lang setup to stop printed warnings

- docker_templates/templates/docker_images/create_drcsim_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzclient_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzserverX_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzserver_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzweb_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros2_core_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros2_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros2_source_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros_image.Dockerfile.em
- docker_templates/templates/snippet/install_upstream_package_list.Dockerfile.em
alternative to #36 
This uses the common denominator in behavior of `os-release` and `lsb-release` on Debian and Ubuntu to not hard-code either the OS name or the OS code name in the containers.
This also implements the suggestion from https://github.com/osrf/docker_templates/pull/36#issuecomment-389660082 to specify the packages needed by the template in the template itself and to allow users to extend the list without adding layers.
To make it explicit that these packages have to be available pstream and not in custom apt repos (ros, osrfoundation etc) I renamed the key to be upstream_packages.
A few notes:
- A change to the docker_images images template will be needed as well to match the new keys
- I didnt modify the legacy ros images accorgingly for now as I dont expect them to be …
> Experiment upstream packages

- docker_templates/folders.py
- docker_templates/library.py
Currently running `create_dockerfolders()` with `auto` generates files for EOL distros.
As we don't want to commit any modification to files we dont build image for, this makes sure that if a given os doesnt have any tag we hook and image generation all at once
Second commit is not really related but fixes a typo related to emtpy tag lists
> Prevent Dockerfile generation for EOL distro / platforms

- docker_templates/templates/docker_images/create_ros2_core_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros2_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros2_ros1_bridge_image.Dockerfile.em
- docker_templates/templates/docker_images/ros1_bridge_entrypoint.sh
- docker_templates/templates/docker_images/ros2_entrypoint.sh
The goal of this PR is to:
- Not have conflicting declaration of `ROS_DISTRO` between ROS 1 and ROS 2 images (`ROS_DISTRO` should always reflect the distribution of ROS the image is based on)
- Not rely on ROS1 repository for any "pure ROS 2" images
To do so this PR:
- create a new template for the ros1-bridge image, the only one supposed to mix ros distributions
- renames ROS2_DISTRO to ROS_DISTRO in all iimages
- create a ROS1_DISTRO env var only in the ros1-bridge images
- remove the ROS 1 apt repository from the "pure ROS 2" images
Related to https://github.com/osrf/docker_images/issues/187
Before being ready for review:
Needs some testing and the corresponding PR on `docker_images` to adapt the `images.yaml.em` template to use the new template for the bridge image
> Homogenize ROS_DISTRO

- docker_templates/templates/docker_images_ros2/source/create_ros_image.Dockerfile.em
If rosdep is to be installed but `rosdistro_index_url` is unset, then avoid setting the environment variable but still initialize rosdep
> Always init rosdep if it is installed

- docker_templates/templates/docker_images_ros2/source/create_ros_image.Dockerfile.em
As the initialization of rosdep should not be impacted by skip in the absence of `vcs` in the template parameters
The generated ros2 source Dockerfile will be identical as we specify both rosdep and vcs for that image
> pull rosdep out of vcs scope

- docker_templates/templates/snippet/vcs_import.Dockerfile.em
Follow up of #53 
Otherwise template expansion fails with
```
AttributeError in template 'snippet/vcs_import.Dockerfile.em': 'NoneType' object has no attribute 'split'
```
> missing empy delimiter

- docker_templates/templates/docker_images/create_base_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzserverX_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/source/create_ros_image.Dockerfile.em
- docker_templates/templates/snippet/install_ros_bootstrap_tools.Dockerfile.em
This allow install only the bootstrap tools relevant for the distro (e.g. not installing rosinstall and vcstools in ROS 1).
Adding rosdep and colcon here also allows to not have to specify it in the config of each image using it (e.g. https://github.com/osrf/docker_images/blob/086440f267921cf4ff39e90bb8e07c81e243dddc/ros2/source/images.yaml.em#L20)
> use template for ROS bootstrap tools installation

- docker_templates/templates/docker_images_ros2/source/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/source/ros_entrypoint.sh
Changes to source template to be used for ros2:source and ros2:devel image
Builds on top of https://github.com/osrf/docker_templates/pull/52
Changes:
- always initialize rosdep https://github.com/osrf/docker_templates/commit/74bc05c5e4ec332faa4c888d9b777fcf6ed0e4e7
- deduplicate WORKDIR https://github.com/osrf/docker_templates/commit/b1946721b4c611970b55807c1279921e7b3b6f88
- homogenize entrypoint to be the same as official images: https://github.com/osrf/docker_templates/commit/e82733f1aecbcd98e71e6d40defe99385f62a31e
> Ros2 devel

- docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/nightly/ros_entrypoint.sh
Rebased and modified version of https://github.com/osrf/docker_templates/pull/49
This PR includes the commits of https://github.com/osrf/docker_templates/pull/51 https://github.com/osrf/docker_templates/pull/52 https://github.com/osrf/docker_templates/pull/53 https://github.com/osrf/docker_templates/pull/54
It builds on top of the commits from #49 and will replace #49 
Once the PR it depends on it'll be rebased to include only the following changes
Relevant Changes:
- original commits from 49 adding the nightly template:
https://github.com/osrf/docker_templates/commit/99bf86637820011141587c5e9de76c1a2d8b6c51 and https://github.com/osrf/docker_templates/commit/7331d8ec72f7ff9b73cfdb9cf8196a70f71c352e
- declare wget as template dependency: …
> Ros2 nightly rebased

- docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/devel/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em
Update ros2 templates with latest signing key for ROS 2 apt repositories.
Context: https://discourse.ros.org/t/key-rotation-for-ros-2-apt-repositories/9363
> Rotate keys for ros2 apt repos

- docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
This should be merged and run after the ROS 1 sync that will rotate keys. It's the same new key as used for the ROS 2 repositories.
https://discourse.ros.org/t/security-issue-on-ros-build-farm/9342/8
> Rotate ROS repository keys.

- docker_templates/templates/docker_images_legacy/create_ros_core_image.Dockerfile.em
~~Requires https://github.com/ros-infrastructure/ros_buildfarm/pull/637~~
Now that this template will start being used on more recent distros as well as non Ubuntu distros. We should not apply the sed for `old-releases` unconditionnaly.
This PR switches to using the [template used by the ros_buildfarm](https://github.com/ros-infrastructure/ros_buildfarm/blob/fe6ee2ad3ec318879a3b9e2831d2a2508430c00f/ros_buildfarm/templates/snippet/old_release_set.Dockerfile.em) instead
@nuclearsandwich FYI
> use ros_buildfarm old_release_set.Dockerfile.em

- docker_templates/templates/docker_images_legacy/create_ros_core_image.Dockerfile.em
The changes described in https://discourse.ros.org/t/security-issue-on-ros-build-farm/9342/8 will remove unsupported ROS releases from the live ROS repositories. The packages for these releases are being migrated to the ROS Snapshots repositories.
This switches legacy releases to adding the snapshots key and using the snapshots http format for final snapshots.
> Legacy ROS releases have been moved to the snapshots repo.

- docker_templates/packages.py
The current regex relies on finding the package in the APT Packages file and use the following line as the version line.
This works for `packages.ros.org` but fails on the `snapshots.ros.org` repository. (the following line is `Priority: extra`)
This PR modifies the regex to capture all the lines until the next empty line (all the package information) and extract the version number from the multiline test block captured.
To do so I modified the version pattern to expect `Version:` at the beginning of the line, and the package pattern to capture until the next empty line (`\n\n`)
> Fixup regexes for version extraction

- docker_templates/eol_distro.py
- docker_templates/packages.py
- docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_legacy/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/ros1_bridge/create_ros_ros1_bridge_image.Dockerfile.em
- docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em
This is WIP, based on https://github.com/osrf/docker_templates/pull/66 and a partial implementation to address the migration of EOL distros to the snapshots repository (https://github.com/osrf/docker_images/issues/281).
WIll update this description as work progresses
> Snippet for setting up APT repos based on if the distro is EOL or not

- docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em
As per docker guidelines: https://github.com/docker-library/official-images/pull/6401#issuecomment-517497515
Tested on trusty and boxturtle/lucid
> use full apt key fingerprint for snapshots repository

- docker_templates/eol_distro.py
Bouncy is now EOL and its packages available on the snapshots repository https://github.com/osrf/docker_images/pull/301#issuecomment-518346213
> add ros bouncy to eol list

- docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em
similar to https://github.com/osrf/docker_images/pull/326
> revert ROS_PACKAGE_PATH hack allowing rosdep to find the ros2 packages

- docker_templates/eol_distro.py
- docker_templates/packages.py
- docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
- docker_templates/templates/snippet/bootstrap_rosdep.Dockerfile.em
- docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em
Adds the `--include-eol-distros` flag if the distro is EOL
> add snippet for bootstrapping rosdep

- docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em
Fixes osrf/docker_images#331
This is an alternative thought of by @dirk-thomas.
Instead of using setup scripts from the `ros-eloquent-ros-workspace` debian package, it downloads and installs the latest version of `ros_workspace`. That way when there are changes to `ros_workspace` or the packages it depends on (`ament_package`, `ament_cmake_core`), the nightly version of those packages continues to be used.
More context/options here https://github.com/osrf/docker_templates/pull/55/files#r268011402
> Build ros_workspace instead of installing deb

- docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/devel/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/nightly/create_ros_nightly_overlay.Dockerfile.em
- docker_templates/templates/snippet/check_pytest_regression.Dockerfile.em
- docker_templates/templates/snippet/setup_colcon_mixin_metadata.Dockerfile.em
The source and nightly images started diverging significantly from the templates, and the nightly-rmw* images dont have a template of their own.
New snppets:
- setup up colcon mixin and metadata
- test that pytest is found
Templates now take `env_before` and `env_after` to pass env vars that the template should define
diff after this PR with images that will land on master
```diff
diff --git a/ros2/nightly/nightly/Dockerfile b/ros2/nightly/nightly/Dockerfile
index a04e35c..c2a7bc5 100644
--- a/ros2/nightly/nightly/Dockerfile
+++ b/ros2/nightly/nightly/Dockerfile
@@ -105,15 +105,9 @@ RUN . /opt/ros/$ROS_DISTRO/setup.sh \
rti-connext-dds-5.3.1" \
&& rm -rf /var/lib/apt/lists/*
-# FIXME Remove this once rosdep detects ROS 2 packages https://github.com/ros-infrastructure/rosdep/issues/660
-# …
```
> Reconcile templates and generated files + add nightly templates

- docker_templates/library.py
Currently the path used for checking commit hashes is the base path of the distro/arch e.g.
`ros/eloquent/ubuntu/bionic` and this same path is used for all tags in the distro.
This leads to unnecessary docker library update when the latest commits didn't touch any of the tags part of the official library.
e.g. for ROS 2 when the ros1-bridge images are updated there is no need to update the manifest as the ros1bridge image is not part of the official library.
With this PR the sha is now checked in the folder of each tag's directory
> fixup commit_path to avoid false positives

- docker_templates/templates/docker_images/create_base_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzclient_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzserver_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzweb_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/ros1_bridge/create_ros_ros1_bridge_image.Dockerfile.em
- docker_templates/templates/snippet/install_ros_bootstrap_tools.Dockerfile.em
- docker_templates/templates/snippet/install_upstream_package_list.Dockerfile.em
- docker_templates/templates/snippet/setup_tzdata.Dockerfile.em
https://discourse.ros.org/t/generating-dev-and-runtime-artefacts-from-ros-packages/12448 reminded me of an old branch adding the use of `no-install-recommends`. While not providing significant improvement it would still reduce image size by about 10%.
This is what is used elsewhere, e.g. for [ROS 2 CI](https://github.com/ros2/ci/blob/36681140b6c4409d5a0532e4e7352ac75ca964e0/linux_docker_resources/Dockerfile)
|             Name              |  Recommends  |   No recommends    |
| ----------------------------- | ------------ | ------------------ |
| melodic-desktop-full-bionic   |   2.9GB      |       2.62GB       |
| melodic-desktop-bionic        |   2.09GB     |       1.85GB       |
| melodic-ros-base-bionic       |   1.26GB     |       1.14GB       |
| melodic-ros-core-bionic       | …
> no install recommends for all apt calls

- docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/nightly/create_ros_nightly_overlay.Dockerfile.em
As of https://github.com/osrf/docker_images/pull/307 the `ros2:nightly*` images use an empty rosdistro index to prevent users from installing released ROS packages via rosdep.
As a consequence, specifying which rosdistro to update brings no benefit as there aren't any distro in the index. Since [rosdep 0.19.0](https://github.com/ros-infrastructure/rosdep/releases/tag/0.19.0), `rosdep update` fails if the `rosdistro` passed to it is unknown.
To fix the build of the nightly images this removes the `--rosdistro` from `rosdep update` in all the nightly images
> don't pass rosdistro when using empty index

- docker_templates/templates/docker_images_ros2/ros1_bridge/create_ros_ros1_bridge_image.Dockerfile.em
As it keeps the same default entry point and command
> Remove redundant directives in ros1 bridge template

- docker_templates/packages.py
While working on https://github.com/osrf/docker_images/issues/376 I came up with this little improvement.
For my connection, it saves >50% time for `ros/create_dockerfiles.py  dir -d ros/melodic/ubuntu/bionic/`
> download Packages.gz instead of Packages

- docker_templates/packages.py
- docker_templates/templates/docker_images/create_drcsim_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzclient_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzserverX_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzserver_image.Dockerfile.em
- docker_templates/templates/docker_images/create_gzweb_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_legacy/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/ros1_bridge/create_ros_ros1_bridge_image.Dockerfile.em
- docker_templates/templates/snippet/label_and_install_package_list.Dockerfile.em
This PR addresses the SHA256 injection as proposed in https://github.com/osrf/docker_images/issues/376
* package handling functions have been refactored (breaks API) to parse the data only once
* getPackageVersions returns list of  `dict(name, version, sha256)` instead string
* Dockerfile templates have been updated to use a common snippet
* whitespace still differs a little bit
* all packages get installed with `apt-get install -y --no-install-recommends`
I can update the common snippet to take a list of ` apt`arguments, if needed.
> inject sha256 labels for all target packages

- docker_templates/packages.py
Before this the extracted sha was always the same for a given gazebo version. For example in https://github.com/osrf/docker_images/pull/467 the sha of the package `gazebo9` was used for all images and packages, even for package  `libgazebo9-dev`
> fix gazebo package lookup resulting in the right shas being used

- docker_templates/eol_distro.py
- docker_templates/templates/docker_images_ros2/devel/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/nightly/create_ros_image.Dockerfile.em
- docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em
- Add eloquent and debian stretch to EOL list
- Use "setup_ros_sources" snippet in ROS 2 images
- Modify "setup_ros_source" template to swap key setup and source.list
Required to generate files of PRs https://github.com/osrf/docker_images/pull/538  https://github.com/osrf/docker_images/pull/537 https://github.com/osrf/docker_images/pull/536
> EOL stretch and swap apt key and source list

- docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em
Follow-up of https://github.com/osrf/docker_templates/pull/97 that broke ROS automatic image generation
> dont crash if testing_repo variable doesnt exist

- docker_templates/eol_distro.py
Dashing is now EOL: https://discourse.ros.org/t/new-packages-and-patch-release-for-ros-2-dashing-diademata-2021-06-10-final/20875
> add dashing to list of EOL distros

- docker_templates/eol_distro.py
As kinetic is now officially EOL: https://discourse.ros.org/t/kinetic-kame-officially-end-of-life/20394
There doesn't seem to be a final snapshot for kinetic yet so this PR cannot be merged for now. /cc @tfoote @nuclearsandwich
> add kinetic to the list of EOL distros

- docker_templates/eol_distro.py
Galactic is EOL and the final snapshot for it has been published:
http://snapshots.ros.org/galactic/final/ubuntu/
> Add Galactic to EOL distros.

- docker_templates/eol_distro.py
- docker_templates/packages.py
- docker_templates/templates/docker_images/create_base_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/create_ros_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/ros1_bridge/create_ros_ros1_bridge_image.Dockerfile.em
- docker_templates/templates/snippet/install_ros_bootstrap_tools.Dockerfile.em
- docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em
- setup.py
Part of https://github.com/osrf/docker_images/issues/406
Here we can leverage the ROS distribution name to retrieve things like ROS version, Python major version and eol status.
This will allow us to remove some hardcoding we had to do left and right to handle sublte changes between ROS 1, ROS2 and ROS1 versions using python3.
The main gain is that we will not have to come update the hardcoded list of ROS EOL distros anymore.
However this implies downloading and parsing the [rosdistro global index file](https://github.com/ros/rosdistro/blob/4ffd760fc7b230106affaa469dc6e9b1e9672297/index-v4.yaml) in a couple places. Doesnt seem like a big deal to me as the file is tiny and multiple parts of the generation pipeline require fetching info from outside sources
> Using rosdistro infos to get ros version, python version and eol status

- docker_templates/packages.py
snapshots.ros.org now provide os-named folders (e.g. http://snapshots.ros.org/melodic/final/debian/dists/).
As opposed to packages.ros.org that places everything in the "ubuntu" folder
In the future they will likely not mirror the debian packages in the ubuntu folder: e.g. upcoming buster final snapshot: http://snapshots.ros.org/noetic/final/ so this PR makes us point to the right place.
Although looking at previous snapshots of ROS Noetic I dont see the debian folder but also cant find buster in the ubuntu folder distro list so maybe I'm missing something here.
@nuclearsandwich Does this PR seems appropriate to you ?
---
PR tested successfully on melodic / stretch
> Use os-named folder for snapshots repos package retrieval

- docker_templates/eol_distro.py
ROS buildfarm will stop building Buster packages shortly https://github.com/ros-infrastructure/ros_buildfarm_config/pull/221
We should switch to the snapshots repos a build a last image on dockerhub before retiring.
@sloretz (@nuclearsandwich ?) do you know when the debs of the last sync with debian Buster packages will be pushed to the snapshots apt repository under the final tag ?
Related to https://github.com/osrf/docker_images/issues/660
> add buster to list of EOL distros

- docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em
This will allow to rebuild images and make them pull the new gpg key as the old one expired
One of the approaches to deal with https://github.com/osrf/docker_images/issues/697
> setup key before source list to force rebuild

- docker_templates/templates/docker_images/create_gzserver_image.Dockerfile.em
- docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em
First step to adress https://github.com/osrf/docker_images/issues/621
This update the template for the gzserver image as well as the common snippet used for all ROS images to use gpg directly instead of apt-key
Needed by https://github.com/osrf/docker_images/pull/705
Following recommendations from https://github.com/docker-library/official-images/pull/15809#issuecomment-1846053036
> use gpg keyrings instead of apt-key

- docker_templates/templates/docker_images/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/create_ros_core_image.Dockerfile.em
- docker_templates/templates/docker_images_ros2/ros1_bridge/create_ros_ros1_bridge_image.Dockerfile.em
- docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em
Follow-up of https://github.com/osrf/docker_templates/pull/109
ROS is now providing key packages: https://discourse.ros.org/t/ros-signing-key-expiracy/43826
But the keys expire on June 1st so this is becoming very urgent.
This PR is still not working, some things to figure out:
- why is the deb download not working in docker build
- why is the package installation failing wit following error message:
```
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Could not read meta data from /tmp/ros1-apt-source.deb
E: The package lists or status file could not be parsed or opened.
```
- how to make a less ugly way to retrieve et propagate the deb version as it's unreadable in the current state
- What to do with snapshots repository ? I cant …
> [WIP] test installing the ros(2)-apt-source packages

- docker_templates/templates/snippet/setup_ros_sources.Dockerfile.em
This embeds everything at template generation time instead of at build time. 
As per the discussion in https://github.com/docker-library/official-images/pull/19162
The template genration is failing on Noetic right now due to the Noetic EOL logic. I don't think that the new index is updated on snapshots for it yet. 
I'm going to look at if #116 will  fix that if merged into this.
> Embedding version hash and distro in string
